
services:
  # PostgreSQL - Banco de dados
  postgres:
    image: postgres:latest
    container_name: postgres-laravel
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: projetopratico
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-network

  # Laravel (PHP + Apache)
  app:
    image: webdevops/php-apache:8.2
    container_name: app-laravel
    working_dir: /var/www/html
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public 
    volumes:
      - ./:/var/www/html
    ports:
      - "8001:80"
    networks:
      - laravel-network
    depends_on:
      - postgres
      - minio

  # Min.io - S3 Storage Local
  minio:
    image: minio/minio
    container_name: minio-laravel
    ports:
      - "9002:9000"       # API S3
      - "9001:9001"       # Console Web MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - laravel-network

volumes:
  postgres-data:
  minio-data:

networks:
  laravel-network:
